#fisier folosit pentru compilarea serverului&clientului TCP iterativ

all:
	gcc [SV]WeatherMonitor.c -o [SV]WeatherMonitor
	gcc [CL]WeatherMonitor.c -o [CL]WeatherMonitor
clean:
	rm -f *~[SV]WeatherMonitor [CL]WeatherMonitor
